name: compile-for-platform
on: [push]
jobs:
  compile-for-platform:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-latest, windows-latest, ubuntu-latest]
        compile-profile: [dev, release]
        include:
          - target: aarch64-apple-darwin
            runs-on: macos-latest
    runs-on: ${{matrix.runs-on}}
    steps:
      - run: sudo apt-get install -y libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev libudev-dev pkg-config
        if: ${{matrix.runs-on == 'ubuntu-latest'}}
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{matrix.target}}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile ${{matrix.compile-profile}} --all-features
